import type { Metadata } from "next";
import "./globals.css";; // make sure this path is correct
// import { Inter} from 'next/font/google';

// const inter = Inter({
//   subsets:['latin'],
//   weight:['400', '700' ],
//   variable:'--font-inter',
//   display: 'swap',
// });
export const metadata: Metadata = {
  title: "Waste Bin Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}


// import type { Metadata } from "next";
// import { Geist, Geist_Mono , Inter } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


